### ISSUE TITLE
Undefined var "creds"

### ISSUE THREAD

**Issue by herdir** [jrosa770/cisco_ios-no_role#1]
Hi,
I was trying to use the network_cli but I have a error message : 
fatal: [LAB-S01]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'creds' is undefined\n\nThe error appears to have been in '/home/user/ios_upgrade/test.yaml': line 16, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set Primary Username and Password\n      ^ here\n"
}

It seems that the task  cannot see the var creds from secrets.yml.
Do you have the same issue ?

**Comment by jrosa770** [comment]
Sorry just saw this after all this time. 
You may have solved by now. But just in case.

If your Get credentials, for example, looks like this:
  - name: obtain login credentials
    include_vars: secrets.yml

Make sure that the syntax is:
--
creds:
 username: 'ansible'
 password: '@ns1bl3'

Also, make sure that the secrets.yml file is in the right path
In this example, secrets.yml is in the same folder as the playbook.
